# Generated by Django 4.2.22 on 2025-06-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_asset_expense_income_gross_income_net_income_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='deductions',
            field=models.FloatField(null=True),
        ),
    ]
