# Generated by Django 4.2.22 on 2025-06-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_income_deductions'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='recurring',
            field=models.BooleanField(null=True),
        ),
    ]
