# Generated by Django 4.2.22 on 2025-06-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_expense_recurring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('amount', models.FloatField()),
                ('vendor', models.CharField(max_length=100)),
            ],
        ),
    ]
