# Generated by Django 4.2.22 on 2025-06-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
