# Generated by Django 4.2.22 on 2025-06-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_bill_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
