# Generated by Django 4.2.22 on 2025-06-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_bill_end_date_bill_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='inc_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('SALARY', 'Salary'), ('OTHER', 'Other')], default='SALARY', max_length=50),
        ),
    ]
