# Generated by Django 4.2.22 on 2025-06-13 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_income_inc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=100)),
                ('account_num', models.IntegerField()),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('Checking', 'CHECKING'), ('Saving', 'SAVING')], default='Checking', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField(blank=True, null=True)),
                ('account', models.CharField(blank=True, null=True)),
                ('description', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='income',
            name='inc_type',
            field=models.CharField(choices=[('Sale', 'SALE'), ('Salary', 'SALARY'), ('Other', 'OTHER')], default='Salary', max_length=50),
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField(blank=True, null=True)),
                ('memo', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.bankaccount')),
            ],
        ),
    ]
