# Generated by Django 4.2.22 on 2025-06-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_bankaccount_account_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=50)),
                ('credit_limit', models.IntegerField()),
                ('last_four', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
