# Generated by Django 4.2.22 on 2025-06-13 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_bankaccount_description_creditcard_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('Checking', 'CHECKING'), ('Saving', 'SAVING'), ('Investing', 'INVESTING'), ('Retirement', 'RETIREMENT')], default='Checking', max_length=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.bankaccount'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.FloatField(),
        ),
    ]
